# Based on https://github.com/matrix-org/dendrite/blob/master/.github/workflows/docker-hub.yml

name: "Docker Hub - Latest"

on:
  push:
    branches: ["master"]
  pull_request:

env:
  DOCKER_NAMESPACE: matrixdotorg
  PLATFORMS: linux/amd64,linux/arm64
  # Only push if this is develop, otherwise we just want to build
  # On a PR github.ref is the target branch, so don't push for that either
  PUSH: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}

jobs:
  docker-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: ${{ env.PUSH == 'true' }}
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: ${{ env.PUSH }}
          tags: |
            ${{ env.DOCKER_NAMESPACE }}/matrixmon:latest
